---

### 以下配置根据实际情况进行修改 ###


# 部署的数据根目录
data_path: /data/mysql
# 物料在部署机的存放目录
soft_tmp_path: /data/soft/solar_base_install/solar_base_component/mysql
# 物料包名称
version: 0.13.0
exporter_name: mysqld_exporter-{{ version }}.linux-amd64.tar.gz
#mysql root 密码
passwd: '7ujm<KI*'
#mysql app用户密码
app_passwd: 'MBGGr7KK4m_HF_Fw@!99'
#创建Prometheus exporter数据库用户mysqld_exporter

exporter_passwd: 'MBGGr7KK4m_HF_Fw@!99'
