---

# 停止服务
- name: stop mysql
  shell: sh {{ data_path }}/shell/stop.sh
  ignore_errors: True   
# 删除相关数据
- name: delete data
  file: dest={{ item }} state=absent
  with_items:
    # 安装目录
    - '{{ data_path }}'
    # soft
    - '{{ data_path }}/soft/{{ mysql_name }}'
    - '{{ data_path }}/soft/mysql-5.7.32-linux-glibc2.12-x86_64'
    - '/etc/rc.d/init.d/mysqld'
  tags: delete_data
- name: delete data
  file: dest=/etc/my.cnf state=absent

- name: delete profile
  shell: sed -i '/\/data\/mysql\/bin/d' /etc/profile 

