---

### 以下配置根据实际情况进行修改 ###


# 部署的数据根目录
data_path: /data/redis
# 物料在部署机的存放目录
soft_tmp_path: /data/solar_base_commpent/redis
# 物料包名称
version: 1.24.0
exporter_name: redis_exporter-v{{ version }}.linux-amd64.tar.gz
port: 9121
