---

# 检查模块是否已经安装
- name: check prometheus exporter
  stat: path={{ es_worker_path }}/plugins/prometheus-exporter/prometheus-exporter-{{ es_version }}.0.jar
  register: prometheus_exporter
  tags: install_es_plugin
- name: check analysis plugin
  stat: path={{ es_worker_path }}/plugins/analysis-ik/elasticsearch-analysis-ik-{{ es_version }}.jar
  register: analysis
  tags: install_es_plugin
# 拷贝模块包到服务器节点
- name: copy prometheus exporter
  copy: src={{ es_soft_path }}/{{ prometheus_exporter_package_name }} dest={{ es_tmp_path }}
  when: not prometheus_exporter.stat.exists
  tags: install_es_plugin
#拷贝分词器模块到节点
- name: copy analysis 
  copy: src={{ es_soft_path }}/{{ ik_name }} dest={{ es_tmp_path }}
  when: not analysis.stat.exists
  tags: install_ik_plugin
# 安装模块
- name: install prometheus exporter and restart es
  shell: su - {{ es_user }} -c 'cd {{ es_worker_path }}/bin/ && ./elasticsearch-plugin install -b file://{{ es_tmp_path }}/{{ prometheus_exporter_package_name }}'
  when: not prometheus_exporter.stat.exists
  tags: install_es_plugin
  notify: 
    - restart es
- name: install analysis and restart es
  shell: su - {{ es_user }} -c 'cd {{ es_worker_path }}/bin/ && ./elasticsearch-plugin install -b file://{{ es_tmp_path }}/{{ ik_name }}'
  when: not analysis.stat.exists
  tags: install_es_plugin
  notify: 
    - restart es