---

# 服务卸载
- name: uninstall 
  hosts: mongodb_cluster
  become: yes
  become_method: sudo
  remote_user: root
  gather_facts: false
  vars_files: roles/mongodb_install/vars/main.yml
  roles:
    - mongodb_uninstall
