---

# 服务卸载
- name: uninstall 
  hosts: mysql
  become: yes
  become_method: sudo
  remote_user: app
  gather_facts: false
  vars_files: roles/mysql_install/vars/main.yml
  roles:
    - mysql_uninstall
