---

# 服务卸载
- name: uninstall 
  hosts: redis_cluster
  become: yes
  become_method: sudo
  remote_user: root
  gather_facts: false
  vars_files: roles/exporter_install/vars/main.yml
  roles:
    - exporter_uninstall
